### ISSUE TITLE
No issue here just wanted to thank you!

### ISSUE THREAD

**Issue by duartec3000** [Nalsai/SpekFlatpak#13]
Hi!

I'm sorry to bother you with an issue I don't know where else to contact you. I just want to say: many thanks for packaging Spek into a Flatpak it really saved me a lot of headaches.

I'm running an immutable distro based on silverblue/ublue and rpm-fusion doesn't have this package (nor does flathub as you must know) and I need a spectrum analyser to quality check some flac files.

Thank you very much!

**Comment by nalsai** [comment]
Thank you for the message!

I just think that Flatpak is very convenient so I learned it and packaged apps that would otherwise be annoying to install and I quite like isolated and immutable systems.

I want to get Spek into Flathub and it's basically ready. I am just waiting for the next release which is going to have the metainfo file included, so it doesn't need to be maintained separately. Sadly the developer is only working on Spek on and off.

**Comment by illtellyoulater** [comment]
Hi @nalsai, thanks for your work. Any reason though as to why this has not yet been released officially by the spek devs?

**Comment by nalsai** [comment]
There is only one spek dev and they only work on it occasionally. It looked like they were going to create another release but now they are taking a break again.

With a lot of open source software you just have to know and accept that developers do it in their spare time without any compensation. Some people have a lot of time and motivation but others only have little.

**Comment by illtellyoulater** [comment]
I am a dev myself. I know what open source is and I often contribute to open source software.

One whole year has passed since they said they'd release a Flatpak package in a few weeks, so I was just trying to move the waters a little... that's all.
